// AUTO-GENERATED by scripts/build-historical-baselines.mjs
// Source: pre-revamp GA4 "Reports snapshot" CSVs (data is static — old G-id is no longer collecting).
// Re-run: `node scripts/build-historical-baselines.mjs`

import type { HistoricalBaseline } from "@/lib/historical";

export const HISTORICAL_BASELINES: HistoricalBaseline[] = [
  {
    "siteId": "reduce-insurance-dependency",
    "source": "Old Google Analytics property (pre-revamp)",
    "dateRange": {
      "from": "2026-01-01",
      "to": "2026-04-30"
    },
    "monthCount": 4,
    "totals": {
      "activeUsers": 1905,
      "newUsers": 1871,
      "sessions": 1951,
      "pageViews": 2152,
      "eventCount": 6684,
      "keyEvents": 0
    },
    "months": [
      {
        "label": "Jan 2026",
        "from": "2026-01-01",
        "to": "2026-01-31",
        "sourceFile": "rid Jan.csv",
        "totals": {
          "activeUsers": 539,
          "newUsers": 533,
          "sessions": 548,
          "pageViews": 645,
          "eventCount": 1962,
          "keyEvents": 0
        },
        "averageEngagementSecondsPerUser": 4.26,
        "channels": [
          {
            "channel": "Direct",
            "sessions": 512
          },
          {
            "channel": "Organic Search",
            "sessions": 18
          },
          {
            "channel": "Unassigned",
            "sessions": 14
          },
          {
            "channel": "Referral",
            "sessions": 3
          },
          {
            "channel": "Organic Social",
            "sessions": 1
          }
        ],
        "pages": [
          {
            "title": "Reducing Insurance Dependence Academy – Reducing Insurance Dependence Academy",
            "pageViews": 217
          },
          {
            "title": "Practice Growth & Expansion – Reducing Insurance Dependence Academy",
            "pageViews": 29
          },
          {
            "title": "Register – Reducing Insurance Dependence Academy",
            "pageViews": 21
          },
          {
            "title": "Apply To Become A RIDA Supporter! – Reducing Insurance Dependence Academy",
            "pageViews": 17
          },
          {
            "title": "Default User Group – Reducing Insurance Dependence Academy",
            "pageViews": 17
          },
          {
            "title": "Zoom Instructions Guide – Reducing Insurance Dependence Academy",
            "pageViews": 16
          },
          {
            "title": "Bonus System That Works – Reducing Insurance Dependence Academy",
            "pageViews": 15
          },
          {
            "title": "Practice Growth and Expansion – Reducing Insurance Dependence Academy",
            "pageViews": 15
          },
          {
            "title": "Webinar May – Reducing Insurance Dependence Academy",
            "pageViews": 15
          },
          {
            "title": "Is NOW The Right Time To Drop PPO’s? – Reducing Insurance Dependence Academy",
            "pageViews": 14
          },
          {
            "title": "Recession Proofing Your Dental Practice – Reducing Insurance Dependence Academy",
            "pageViews": 14
          },
          {
            "title": "Leading High-Performance Dental Teams & Building a Scalable Practice – Reducing Insurance Dependence Academy",
            "pageViews": 12
          },
          {
            "title": "Webinar July23 – Reducing Insurance Dependence Academy",
            "pageViews": 12
          },
          {
            "title": "Become A Partner – Reducing Insurance Dependence Academy",
            "pageViews": 11
          },
          {
            "title": "Webinar Archive – Reducing Insurance Dependence Academy",
            "pageViews": 11
          },
          {
            "title": "Search Users – Reducing Insurance Dependence Academy",
            "pageViews": 10
          },
          {
            "title": "Events – Reducing Insurance Dependence Academy",
            "pageViews": 9
          },
          {
            "title": "Membership – Reducing Insurance Dependence Academy",
            "pageViews": 9
          },
          {
            "title": "Founding Committee – Reducing Insurance Dependence Academy",
            "pageViews": 7
          },
          {
            "title": "Lost your password? – Reducing Insurance Dependence Academy",
            "pageViews": 6
          }
        ],
        "events": [
          {
            "name": "page_view",
            "eventCount": 645
          },
          {
            "name": "session_start",
            "eventCount": 548
          },
          {
            "name": "first_visit",
            "eventCount": 533
          },
          {
            "name": "scroll",
            "eventCount": 120
          },
          {
            "name": "user_engagement",
            "eventCount": 108
          },
          {
            "name": "click",
            "eventCount": 8
          }
        ],
        "countries": [
          {
            "country": "CN",
            "activeUsers": 434
          },
          {
            "country": "US",
            "activeUsers": 75
          },
          {
            "country": "LK",
            "activeUsers": 7
          },
          {
            "country": "BR",
            "activeUsers": 4
          },
          {
            "country": "CA",
            "activeUsers": 4
          },
          {
            "country": "DE",
            "activeUsers": 4
          },
          {
            "country": "IR",
            "activeUsers": 2
          }
        ],
        "dailyActiveUsers": [
          22,
          20,
          17,
          9,
          22,
          15,
          18,
          17,
          19,
          13,
          12,
          25,
          9,
          21,
          17,
          13,
          20,
          21,
          23,
          12,
          13,
          16,
          12,
          15,
          17,
          13,
          27,
          12,
          32,
          25,
          12
        ],
        "dailyNewUsers": [
          22,
          20,
          17,
          8,
          22,
          15,
          18,
          17,
          19,
          13,
          12,
          24,
          9,
          21,
          17,
          13,
          20,
          21,
          23,
          12,
          13,
          15,
          12,
          15,
          17,
          13,
          27,
          11,
          32,
          23,
          12
        ]
      },
      {
        "label": "Feb 2026",
        "from": "2026-02-01",
        "to": "2026-02-28",
        "sourceFile": "rid feb.csv",
        "totals": {
          "activeUsers": 352,
          "newUsers": 348,
          "sessions": 362,
          "pageViews": 391,
          "eventCount": 1212,
          "keyEvents": 0
        },
        "averageEngagementSecondsPerUser": 2.74,
        "channels": [
          {
            "channel": "Direct",
            "sessions": 344
          },
          {
            "channel": "Organic Search",
            "sessions": 11
          },
          {
            "channel": "Organic Social",
            "sessions": 3
          },
          {
            "channel": "Referral",
            "sessions": 2
          },
          {
            "channel": "Unassigned",
            "sessions": 2
          }
        ],
        "pages": [
          {
            "title": "Reducing Insurance Dependence Academy – Reducing Insurance Dependence Academy",
            "pageViews": 159
          },
          {
            "title": "Webinar Archive – Reducing Insurance Dependence Academy",
            "pageViews": 20
          },
          {
            "title": "Register – Reducing Insurance Dependence Academy",
            "pageViews": 15
          },
          {
            "title": "Membership – Reducing Insurance Dependence Academy",
            "pageViews": 10
          },
          {
            "title": "High-Value Services Clinical Panel – Reducing Insurance Dependence Academy",
            "pageViews": 9
          },
          {
            "title": "Become A Partner – Reducing Insurance Dependence Academy",
            "pageViews": 8
          },
          {
            "title": "Gary Takacs – Reducing Insurance Dependence Academy",
            "pageViews": 8
          },
          {
            "title": "Exclusive RIDA Videos – Reducing Insurance Dependence Academy",
            "pageViews": 7
          },
          {
            "title": "Success Stories – Reducing Insurance Dependence Academy",
            "pageViews": 7
          },
          {
            "title": "Uncategorized – Reducing Insurance Dependence Academy",
            "pageViews": 6
          },
          {
            "title": "Contact – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "Newsletter Archive – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "Resources – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "Webinar Archive – Page 2 – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "Apply To Become A RIDA Supporter! – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Marketing Strategy Meeting – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "PPO Calculator – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Practice Growth & Expansion – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Recession Proofing Your Dental Practice – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Dentists, learn how you can benefit from Dr. Cialdini’s principles – Reducing Insurance Dependence Academy",
            "pageViews": 3
          }
        ],
        "events": [
          {
            "name": "page_view",
            "eventCount": 391
          },
          {
            "name": "session_start",
            "eventCount": 360
          },
          {
            "name": "first_visit",
            "eventCount": 348
          },
          {
            "name": "scroll",
            "eventCount": 65
          },
          {
            "name": "user_engagement",
            "eventCount": 46
          },
          {
            "name": "click",
            "eventCount": 2
          }
        ],
        "countries": [
          {
            "country": "CN",
            "activeUsers": 154
          },
          {
            "country": "SG",
            "activeUsers": 121
          },
          {
            "country": "US",
            "activeUsers": 54
          },
          {
            "country": "LK",
            "activeUsers": 7
          },
          {
            "country": "GB",
            "activeUsers": 4
          },
          {
            "country": "CA",
            "activeUsers": 3
          },
          {
            "country": "DE",
            "activeUsers": 3
          }
        ],
        "dailyActiveUsers": [
          11,
          15,
          6,
          14,
          15,
          18,
          12,
          9,
          8,
          8,
          10,
          24,
          15,
          10,
          17,
          19,
          12,
          12,
          11,
          10,
          15,
          8,
          14,
          17,
          8,
          14,
          12,
          8
        ],
        "dailyNewUsers": [
          11,
          15,
          6,
          14,
          15,
          18,
          11,
          9,
          8,
          8,
          10,
          24,
          15,
          10,
          17,
          18,
          12,
          12,
          11,
          10,
          15,
          8,
          14,
          17,
          8,
          14,
          10,
          8
        ]
      },
      {
        "label": "Mar 2026",
        "from": "2026-03-01",
        "to": "2026-03-31",
        "sourceFile": "rid march.csv",
        "totals": {
          "activeUsers": 610,
          "newUsers": 597,
          "sessions": 624,
          "pageViews": 683,
          "eventCount": 2079,
          "keyEvents": 0
        },
        "averageEngagementSecondsPerUser": 11.46,
        "channels": [
          {
            "channel": "Direct",
            "sessions": 587
          },
          {
            "channel": "Organic Search",
            "sessions": 26
          },
          {
            "channel": "Organic Social",
            "sessions": 9
          },
          {
            "channel": "Referral",
            "sessions": 2
          }
        ],
        "pages": [
          {
            "title": "Page not found – Reducing Insurance Dependence Academy",
            "pageViews": 360
          },
          {
            "title": "Reducing Insurance Dependence Academy – Reducing Insurance Dependence Academy",
            "pageViews": 158
          },
          {
            "title": "Marketing Strategy Meeting – Reducing Insurance Dependence Academy",
            "pageViews": 19
          },
          {
            "title": "Register – Reducing Insurance Dependence Academy",
            "pageViews": 12
          },
          {
            "title": "Membership – Reducing Insurance Dependence Academy",
            "pageViews": 9
          },
          {
            "title": "Webinar Archive – Reducing Insurance Dependence Academy",
            "pageViews": 9
          },
          {
            "title": "Events – Reducing Insurance Dependence Academy",
            "pageViews": 7
          },
          {
            "title": "Dental Marketing – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Summit – Dr. Frances Brelsford – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Summit – Ekwa Marketing – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Summit – Gary Takacs from Thriving Dentist – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Founding Committee – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "Growing Your Practice Made Simple with Bob Affleck and Bonus Tips to Boost New Patients featuring Naren Arulrajah – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "My Account – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "Newsletter Archive – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "Become A Partner – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "Exclusive RIDA Videos – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "Gary Takacs – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "How to control your overhead to 60% or less! – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "Insurance Dependency… Does It Have Two Sides to It? – Reducing Insurance Dependence Academy",
            "pageViews": 2
          }
        ],
        "events": [
          {
            "name": "page_view",
            "eventCount": 683
          },
          {
            "name": "session_start",
            "eventCount": 624
          },
          {
            "name": "first_visit",
            "eventCount": 597
          },
          {
            "name": "user_engagement",
            "eventCount": 100
          },
          {
            "name": "scroll",
            "eventCount": 67
          },
          {
            "name": "click",
            "eventCount": 8
          }
        ],
        "countries": [
          {
            "country": "SG",
            "activeUsers": 494
          },
          {
            "country": "US",
            "activeUsers": 54
          },
          {
            "country": "CN",
            "activeUsers": 18
          },
          {
            "country": "LK",
            "activeUsers": 13
          },
          {
            "country": "CA",
            "activeUsers": 10
          },
          {
            "country": "GB",
            "activeUsers": 3
          },
          {
            "country": "NL",
            "activeUsers": 2
          }
        ],
        "dailyActiveUsers": [
          10,
          6,
          11,
          7,
          7,
          5,
          8,
          9,
          6,
          15,
          5,
          3,
          0,
          0,
          0,
          0,
          161,
          100,
          16,
          10,
          22,
          82,
          23,
          19,
          18,
          9,
          7,
          12,
          8,
          12,
          19
        ],
        "dailyNewUsers": [
          10,
          6,
          11,
          6,
          5,
          5,
          8,
          9,
          6,
          15,
          5,
          3,
          0,
          0,
          0,
          0,
          159,
          99,
          15,
          10,
          22,
          82,
          21,
          19,
          18,
          9,
          7,
          12,
          7,
          10,
          18
        ]
      },
      {
        "label": "Apr 2026",
        "from": "2026-04-01",
        "to": "2026-04-30",
        "sourceFile": "rid april.csv",
        "totals": {
          "activeUsers": 404,
          "newUsers": 393,
          "sessions": 417,
          "pageViews": 433,
          "eventCount": 1431,
          "keyEvents": 0
        },
        "averageEngagementSecondsPerUser": 1.85,
        "channels": [
          {
            "channel": "Direct",
            "sessions": 352
          },
          {
            "channel": "Unassigned",
            "sessions": 29
          },
          {
            "channel": "Organic Search",
            "sessions": 28
          },
          {
            "channel": "Referral",
            "sessions": 4
          },
          {
            "channel": "Organic Social",
            "sessions": 3
          },
          {
            "channel": "Email",
            "sessions": 1
          }
        ],
        "pages": [
          {
            "title": "Reducing Insurance Dependence Academy – Reducing Insurance Dependence Academy",
            "pageViews": 156
          },
          {
            "title": "Page not found – Reducing Insurance Dependence Academy",
            "pageViews": 108
          },
          {
            "title": "Webinar Archive – Reducing Insurance Dependence Academy",
            "pageViews": 14
          },
          {
            "title": "Marketing Strategy Meeting – Reducing Insurance Dependence Academy",
            "pageViews": 11
          },
          {
            "title": "RIDA Blog – Reducing Insurance Dependence Academy",
            "pageViews": 9
          },
          {
            "title": "Events – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "Founding Committee – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "Newsletter Archive – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "RIDA Supporters – Reducing Insurance Dependence Academy",
            "pageViews": 5
          },
          {
            "title": "Contact – Reducing Insurance Dependence Academy",
            "pageViews": 4
          },
          {
            "title": "Become A Partner – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "Exclusive RIDA Videos – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "Podcast – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "Recession Proofing Your Dental Practice – Reducing Insurance Dependence Academy",
            "pageViews": 3
          },
          {
            "title": "All Groups – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "Bob Affleck – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "Membership – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "News Flash: The current dental insurance system is broken – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "PPO Calculator – Reducing Insurance Dependence Academy",
            "pageViews": 2
          },
          {
            "title": "Success Stories – Reducing Insurance Dependence Academy",
            "pageViews": 2
          }
        ],
        "events": [
          {
            "name": "page_view",
            "eventCount": 433
          },
          {
            "name": "session_start",
            "eventCount": 416
          },
          {
            "name": "first_visit",
            "eventCount": 393
          },
          {
            "name": "user_engagement",
            "eventCount": 101
          },
          {
            "name": "scroll",
            "eventCount": 86
          },
          {
            "name": "click",
            "eventCount": 2
          }
        ],
        "countries": [
          {
            "country": "SG",
            "activeUsers": 235
          },
          {
            "country": "US",
            "activeUsers": 104
          },
          {
            "country": "LK",
            "activeUsers": 12
          },
          {
            "country": "DE",
            "activeUsers": 7
          },
          {
            "country": "HK",
            "activeUsers": 6
          },
          {
            "country": "VN",
            "activeUsers": 5
          },
          {
            "country": "ID",
            "activeUsers": 3
          }
        ],
        "dailyActiveUsers": [
          16,
          14,
          27,
          11,
          17,
          48,
          14,
          18,
          23,
          16,
          8,
          8,
          16,
          9,
          12,
          6,
          24,
          5,
          8,
          13,
          10,
          16,
          13,
          16,
          9,
          16,
          11,
          0,
          0,
          0
        ],
        "dailyNewUsers": [
          16,
          12,
          26,
          11,
          17,
          48,
          14,
          18,
          23,
          16,
          8,
          8,
          16,
          9,
          10,
          6,
          24,
          5,
          7,
          12,
          9,
          14,
          13,
          16,
          9,
          15,
          11,
          0,
          0,
          0
        ]
      }
    ]
  },
  {
    "siteId": "dominate-law",
    "source": "Old Google Analytics property (pre-revamp)",
    "dateRange": {
      "from": "2026-01-01",
      "to": "2026-03-31"
    },
    "monthCount": 3,
    "totals": {
      "activeUsers": 447,
      "newUsers": 392,
      "sessions": 550,
      "pageViews": 1106,
      "eventCount": 3049,
      "keyEvents": 0
    },
    "months": [
      {
        "label": "Jan 2026",
        "from": "2026-01-01",
        "to": "2026-01-31",
        "sourceFile": "DL Jan.csv",
        "totals": {
          "activeUsers": 252,
          "newUsers": 239,
          "sessions": 275,
          "pageViews": 403,
          "eventCount": 1199,
          "keyEvents": 0
        },
        "averageEngagementSecondsPerUser": 13.09,
        "channels": [
          {
            "channel": "Direct",
            "sessions": 210
          },
          {
            "channel": "Organic Search",
            "sessions": 62
          },
          {
            "channel": "Referral",
            "sessions": 2
          },
          {
            "channel": "Unassigned",
            "sessions": 1
          }
        ],
        "pages": [
          {
            "title": "Attorney Podcasts | Attorney Marketing Podcasts | Dominate Law",
            "pageViews": 85
          },
          {
            "title": "Dominate Law Podcast Show | Brought to you by Ekwa Marketing",
            "pageViews": 38
          },
          {
            "title": "MSM - Dominate LAW",
            "pageViews": 35
          },
          {
            "title": "Dominate Law | Thriving Attorney Podcast Show - Curious Attorney Minds",
            "pageViews": 28
          },
          {
            "title": "Naren Arulrajah - Host, Dominate Law podcast series.",
            "pageViews": 16
          },
          {
            "title": "Page not found - Dominate LAW",
            "pageViews": 15
          },
          {
            "title": "Contact Us - Free Podcasts - For Attorney",
            "pageViews": 13
          },
          {
            "title": "Guest Form - Dominate LAW",
            "pageViews": 13
          },
          {
            "title": "Pursuing your passions and carving your own path with Joey Vitale - Dominate LAW",
            "pageViews": 11
          },
          {
            "title": "Reviews – Dominate LAW",
            "pageViews": 11
          },
          {
            "title": "My journey to finding happiness in the area of law with Nicole Abboud - Dominate LAW",
            "pageViews": 9
          },
          {
            "title": "Preparing clients for a better deposition in the courtroom with Alan Fanger - Dominate LAW",
            "pageViews": 8
          },
          {
            "title": "Cookie Policy - Dominate LAW",
            "pageViews": 7
          },
          {
            "title": "Get Your Contact - Dominate LAW",
            "pageViews": 7
          },
          {
            "title": "Be the voice for those who need justice with Marilynn Mika Spencer - Dominate LAW",
            "pageViews": 6
          },
          {
            "title": "How to build relationships in the digital age with Mitch Jackson - Dominate LAW",
            "pageViews": 6
          },
          {
            "title": "Privacy Policy - Dominate LAW",
            "pageViews": 6
          },
          {
            "title": "Mexican Law across the World with Oscar Valdez - Dominate LAW",
            "pageViews": 5
          },
          {
            "title": "Mindfulness: How it’s linked to a lawyer’s well-being and why lawyers should practice it with Jeena Cho - Dominate LAW",
            "pageViews": 5
          },
          {
            "title": "The nuts and bolts of how to build and grow a Law Practice with Gary Bennett - Dominate LAW",
            "pageViews": 5
          }
        ],
        "events": [
          {
            "name": "page_view",
            "eventCount": 403
          },
          {
            "name": "session_start",
            "eventCount": 276
          },
          {
            "name": "first_visit",
            "eventCount": 239
          },
          {
            "name": "user_engagement",
            "eventCount": 174
          },
          {
            "name": "scroll",
            "eventCount": 86
          },
          {
            "name": "form_start",
            "eventCount": 12
          },
          {
            "name": "form_submit",
            "eventCount": 5
          },
          {
            "name": "click",
            "eventCount": 4
          }
        ],
        "countries": [
          {
            "country": "CN",
            "activeUsers": 99
          },
          {
            "country": "US",
            "activeUsers": 73
          },
          {
            "country": "DE",
            "activeUsers": 32
          },
          {
            "country": "CA",
            "activeUsers": 15
          },
          {
            "country": "LK",
            "activeUsers": 9
          },
          {
            "country": "IR",
            "activeUsers": 5
          },
          {
            "country": "NL",
            "activeUsers": 5
          }
        ],
        "dailyActiveUsers": [
          1,
          8,
          2,
          2,
          22,
          16,
          3,
          4,
          2,
          2,
          8,
          11,
          3,
          11,
          4,
          4,
          23,
          42,
          7,
          2,
          2,
          38,
          8,
          0,
          4,
          4,
          5,
          6,
          5,
          2,
          1
        ],
        "dailyNewUsers": [
          1,
          8,
          1,
          3,
          22,
          15,
          3,
          4,
          2,
          2,
          6,
          10,
          3,
          9,
          4,
          4,
          23,
          42,
          7,
          2,
          2,
          37,
          7,
          0,
          4,
          3,
          4,
          3,
          5,
          2,
          1
        ]
      },
      {
        "label": "Feb 2026",
        "from": "2026-02-01",
        "to": "2026-02-28",
        "sourceFile": "DL feb.csv",
        "totals": {
          "activeUsers": 80,
          "newUsers": 71,
          "sessions": 105,
          "pageViews": 178,
          "eventCount": 535,
          "keyEvents": 0
        },
        "averageEngagementSecondsPerUser": 20.42,
        "channels": [
          {
            "channel": "Direct",
            "sessions": 60
          },
          {
            "channel": "Organic Search",
            "sessions": 43
          },
          {
            "channel": "Organic Video",
            "sessions": 1
          },
          {
            "channel": "Referral",
            "sessions": 1
          }
        ],
        "pages": [
          {
            "title": "Attorney Podcasts | Attorney Marketing Podcasts | Dominate Law",
            "pageViews": 67
          },
          {
            "title": "Dominate Law Podcast Show | Brought to you by Ekwa Marketing",
            "pageViews": 41
          },
          {
            "title": "Naren Arulrajah - Host, Dominate Law podcast series.",
            "pageViews": 17
          },
          {
            "title": "Dominate Law | Thriving Attorney Podcast Show - Curious Attorney Minds",
            "pageViews": 13
          },
          {
            "title": "Contact Us - Free Podcasts - For Attorney",
            "pageViews": 8
          },
          {
            "title": "Reviews – Dominate LAW",
            "pageViews": 7
          },
          {
            "title": "Guest Form - Dominate LAW",
            "pageViews": 4
          },
          {
            "title": "Page not found - Dominate LAW",
            "pageViews": 4
          },
          {
            "title": "Marketing Strategy Meeting - Dominate LAW",
            "pageViews": 3
          },
          {
            "title": "Preparing clients for a better deposition in the courtroom with Alan Fanger - Dominate LAW",
            "pageViews": 3
          },
          {
            "title": "Cookie Policy - Dominate LAW",
            "pageViews": 2
          },
          {
            "title": "MSM - Dominate LAW",
            "pageViews": 2
          },
          {
            "title": "My journey to finding happiness in the area of law with Nicole Abboud - Dominate LAW",
            "pageViews": 2
          },
          {
            "title": "How to build relationships in the digital age with Mitch Jackson - Dominate LAW",
            "pageViews": 1
          },
          {
            "title": "Privacy Policy - Dominate LAW",
            "pageViews": 1
          },
          {
            "title": "Pursuing your passions and carving your own path with Joey Vitale - Dominate LAW",
            "pageViews": 1
          },
          {
            "title": "The Business side of a Law Firm with Larry Organ - Dominate LAW",
            "pageViews": 1
          },
          {
            "title": "The purpose & impacts of being a divorce lawyer with Kelly Chang Rickert - Dominate LAW",
            "pageViews": 1
          }
        ],
        "events": [
          {
            "name": "page_view",
            "eventCount": 178
          },
          {
            "name": "user_engagement",
            "eventCount": 113
          },
          {
            "name": "session_start",
            "eventCount": 105
          },
          {
            "name": "first_visit",
            "eventCount": 71
          },
          {
            "name": "scroll",
            "eventCount": 59
          },
          {
            "name": "click",
            "eventCount": 9
          }
        ],
        "countries": [
          {
            "country": "US",
            "activeUsers": 24
          },
          {
            "country": "CN",
            "activeUsers": 15
          },
          {
            "country": "SG",
            "activeUsers": 14
          },
          {
            "country": "CA",
            "activeUsers": 6
          },
          {
            "country": "LK",
            "activeUsers": 4
          },
          {
            "country": "DE",
            "activeUsers": 2
          },
          {
            "country": "GB",
            "activeUsers": 2
          }
        ],
        "dailyActiveUsers": [
          2,
          5,
          4,
          3,
          1,
          2,
          1,
          0,
          4,
          5,
          2,
          2,
          2,
          1,
          4,
          4,
          6,
          3,
          3,
          2,
          2,
          1,
          6,
          6,
          5,
          1,
          2,
          1
        ],
        "dailyNewUsers": [
          2,
          4,
          4,
          2,
          1,
          2,
          1,
          0,
          3,
          4,
          1,
          2,
          2,
          1,
          4,
          4,
          6,
          2,
          2,
          2,
          2,
          1,
          6,
          5,
          4,
          1,
          2,
          1
        ]
      },
      {
        "label": "Mar 2026",
        "from": "2026-03-01",
        "to": "2026-03-31",
        "sourceFile": "DL march.csv",
        "totals": {
          "activeUsers": 115,
          "newUsers": 82,
          "sessions": 170,
          "pageViews": 525,
          "eventCount": 1315,
          "keyEvents": 0
        },
        "averageEngagementSecondsPerUser": 46.48,
        "channels": [
          {
            "channel": "Organic Search",
            "sessions": 103
          },
          {
            "channel": "Direct",
            "sessions": 35
          },
          {
            "channel": "Organic Social",
            "sessions": 18
          },
          {
            "channel": "Referral",
            "sessions": 9
          },
          {
            "channel": "Display",
            "sessions": 5
          }
        ],
        "pages": [
          {
            "title": "Attorney Podcasts | Attorney Marketing Podcasts | Dominate Law",
            "pageViews": 145
          },
          {
            "title": "Dominate Law Podcast Show | Brought to you by Ekwa Marketing",
            "pageViews": 127
          },
          {
            "title": "Dominate Law | Thriving Attorney Podcast Show - Curious Attorney Minds",
            "pageViews": 41
          },
          {
            "title": "Contact Us - Free Podcasts - For Attorney",
            "pageViews": 22
          },
          {
            "title": "Preparing clients for a better deposition in the courtroom with Alan Fanger - Dominate LAW",
            "pageViews": 19
          },
          {
            "title": "Naren Arulrajah - Host, Dominate Law podcast series.",
            "pageViews": 18
          },
          {
            "title": "Reviews – Dominate LAW",
            "pageViews": 17
          },
          {
            "title": "Page not found - Dominate LAW",
            "pageViews": 12
          },
          {
            "title": "Guest Form - Dominate LAW",
            "pageViews": 10
          },
          {
            "title": "MSM - Dominate LAW",
            "pageViews": 8
          },
          {
            "title": "Privacy Policy - Dominate LAW",
            "pageViews": 8
          },
          {
            "title": "The Journey & Experiences of being a Lawyer with Gary Bennett - Dominate LAW",
            "pageViews": 8
          },
          {
            "title": "My journey to finding happiness in the area of law with Nicole Abboud - Dominate LAW",
            "pageViews": 7
          },
          {
            "title": "Pursuing your passions and carving your own path with Joey Vitale - Dominate LAW",
            "pageViews": 6
          },
          {
            "title": "Using your Passion to Help People get Justice with James DeSimone - Dominate LAW",
            "pageViews": 6
          },
          {
            "title": "How to build relationships in the digital age with Mitch Jackson - Dominate LAW",
            "pageViews": 5
          },
          {
            "title": "Making Time Personally And Professionally with Lisa Maki - Dominate LAW",
            "pageViews": 5
          },
          {
            "title": "Mindfulness: How it’s linked to a lawyer’s well-being and why lawyers should practice it with Jeena Cho - Dominate LAW",
            "pageViews": 5
          },
          {
            "title": "The nuts and bolts of how to build and grow a Law Practice with Gary Bennett - Dominate LAW",
            "pageViews": 5
          },
          {
            "title": "Always look from the other perspective and provide value in the work you do with Daniel Forouzan - Dominate LAW",
            "pageViews": 4
          }
        ],
        "events": [
          {
            "name": "page_view",
            "eventCount": 525
          },
          {
            "name": "user_engagement",
            "eventCount": 378
          },
          {
            "name": "session_start",
            "eventCount": 170
          },
          {
            "name": "scroll",
            "eventCount": 148
          },
          {
            "name": "first_visit",
            "eventCount": 82
          },
          {
            "name": "click",
            "eventCount": 12
          }
        ],
        "countries": [
          {
            "country": "US",
            "activeUsers": 46
          },
          {
            "country": "LK",
            "activeUsers": 16
          },
          {
            "country": "CA",
            "activeUsers": 7
          },
          {
            "country": "SG",
            "activeUsers": 5
          },
          {
            "country": "CN",
            "activeUsers": 3
          },
          {
            "country": "IE",
            "activeUsers": 3
          },
          {
            "country": "GB",
            "activeUsers": 2
          }
        ],
        "dailyActiveUsers": [
          0,
          2,
          0,
          4,
          5,
          3,
          1,
          2,
          4,
          8,
          5,
          4,
          2,
          0,
          3,
          5,
          9,
          5,
          5,
          1,
          1,
          16,
          9,
          4,
          3,
          1,
          6,
          0,
          3,
          1,
          3
        ],
        "dailyNewUsers": [
          0,
          2,
          0,
          3,
          4,
          2,
          1,
          2,
          2,
          6,
          4,
          3,
          2,
          0,
          1,
          2,
          6,
          4,
          4,
          1,
          1,
          15,
          6,
          0,
          2,
          0,
          4,
          0,
          1,
          1,
          3
        ]
      }
    ]
  }
];
